### ISSUE TITLE
Hacktoberfest 2024

### ISSUE THREAD

**Issue by ns-rse** [SheffieldR/SheffieldR.github.io#50]
Organise four weekly slots throughout October for people to contribute to R projects via [Hacktoberfest 2024](https://hacktoberfest.com/).

## Dates

+ [ ] #51 2024-10-04 17:00-18:30 Kickoff - Intro to Git (fork, commit, push and pull-request); finding issues.
+ [ ] #52 2024-10-11 12:30-13:30 - Hybrid session, work on issues, support with questions
+ [ ] #53 2024-10-18 12:30-13:30 - Hybrid session, work on issues, support with questions
+ [ ] #54 2024-10-25 12:30-13:30 - Hybrid session, work on issues, support with questions
